### ISSUE TITLE
total memory and cpu display on web and terminal

### ISSUE THREAD

**Issue by steinsgateted** [grycap/oscar#159]
### Describe the solution you'd like

Now total memory and cpu can be obtained from edit service page or yunikorn-configs.

[https://localhost/ui/#/services](https://localhost/ui/#/services) and `oscar-cli service list` do not display total memory and cpu.

### References

**Comment by srisco** [comment]
Hi @steinsgateted thanks for the point. YuniKorn configuration fields haven't been implemented in the web interface yet. However, the latest release of [OSCAR-CLI](https://github.com/grycap/oscar-cli/releases/tag/v1.3.0) supports them, please update it and let me know if you can configure YuniKorn queues properly.

Regards.

**Comment by steinsgateted** [comment]
Hi @srisco,
Thank you for the explanation.
I can see the information of total memory and cpu in `oscar-cli service get imagemagick`.
But there is no total memory and cpu in `oscar-cli service list`

Regards.

**Comment by gmolto** [comment]
This is already shown in the OSCAR CLI. I am closing this issue.
