### ISSUE TITLE
Restrict the Origin of Docker Images to a Set of Repositories 

### ISSUE THREAD

**Issue by gmolto** [grycap/oscar#214]
### Describe the solution you'd like

Currently, an OSCAR service can be created out of an arbitrary Docker image from a repository. The owner of the OSCAR cluster may want to limit the scope of the Docker images employed to those available in a curated set of Docker image repositories (e.g. deephdc/\*). A list of repositories and the usage of wildcards should be supported (e.g. deephdc/deep-oc-posenet-\*) for greater flexibility.

**Comment by gmolto** [comment]
Requested by Ignacio

**Comment by catttam** [comment]
Feature added on release [v3.1.0](https://github.com/grycap/oscar/releases/tag/v3.1.0)
