### ISSUE TITLE
Unable to Process Files with Unicode Characters

### ISSUE THREAD

**Issue by gmolto** [grycap/oscar#40]
After trying to upload a file with a non-ascii character to an input bucket, the pod responsible to process the file fails with the following message:

```sh
sudo kubectl logs oscar-image-to-gray-708ad53a-0e7f-4c98-bcba-270c51862c90-zgqq9 -n oscar-fn
[7] Failed to execute script to_build
Traceback (most recent call last):
  File "to_build.py", line 106, in <module>
  File "to_build.py", line 94, in get_stdin
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 624: ordinal not in range(128)
```
The input file was named: "Foto cuádruple el 01-05-16 a las 10.57 #6"

**Comment by srisco** [comment]
New OSCAR versions using [faas-supervisor](https://github.com/grycap/faas-supervisor/) don't seem to have this problem. 

Remember also that you must create the user-scripts as shown in #81.
