### ISSUE TITLE
Mismatch between SCAR_OUTPUT_DIR and SCAR_OUTPUT_FOLDER

### ISSUE THREAD

**Issue by gmolto** [grycap/oscar#42]
SCAR examples assume the existence of the environment variable SCAR_OUTPUT_DIR while OSCAR examples assume the existence of the variable SCAR_OUTPUT_FOLDER. We should use the same convention so that we can reuse the same script files across frameworks.

**Comment by alpegon** [comment]
Fixed in PR #76.
Now the environment variables used are TMP_INPUT_DIR / TMP_OUTPUT_DIR
